-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "caption" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT;
